version: '2'

services:
  angular:
    build: frontend
    ports:
      - "80:80"

  express:
    build: backend
    ports:
      - "3000:3000"
    # links:
    #   - database

  # database:
  #   image: mongo
  #   ports:
  #     - "27017:27017"